import React from 'react';
import ReactDOM from 'react-dom/client';
import './components/arc/foundation.css';
import './styles.css';
import App,{AuthCallback} from './App';
const callback=window.location.pathname==='/auth/callback';
const params=callback?new URLSearchParams(window.location.search):null;
const slt=params?.get('slt')||null;const state=params?.get('state')||null;
if(callback)window.history.replaceState(null,'','/auth/callback');
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{callback?<AuthCallback slt={slt} state={state}/>:<App/>}</React.StrictMode>);
